apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
 - name: quay.apps.ocp4-8.infocepo.com/ministere-interieur-prj-plec/app-nginx-static-demo:master
   newName: quay.apps.ocp4-8.infocepo.com/ministere-interieur-demon/app-nginx-static-demo
   newTag: master

patches:
  - target:
      kind: Ingress
      name: forge-mi-ingress-base-static
    path: ./patches/ingress.yaml